/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LectorArchivo;
import java.util.ArrayList;
import java.util.List;
import modelo.*;
/**
 *
 * @author SRG98
 */
public class Computador extends javax.swing.JFrame {
    private CPU cpu;
    private ModuloES moduloES;
    private MemoriaPrincipal memoriaPrincipal;
    private UnidadControl unidadControl;
    private LectorArchivo lector;
    private int contadorSiguiente;
    /**
     * Creates new form Ventana
     */
    public Computador() {
        initComponents();
        lector=new LectorArchivo();
        contadorSiguiente=0;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spEntrada = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        btnSiguiente = new javax.swing.JButton();
        spSalida = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        txtOP2 = new javax.swing.JTextField();
        txtIR = new javax.swing.JTextField();
        txtOP1 = new javax.swing.JTextField();
        txtResultadoALU = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtMBR = new javax.swing.JTextField();
        txtMAR = new javax.swing.JTextField();
        btnEntrada = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(3088, 1416));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEntrada.setEditable(false);
        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        spEntrada.setViewportView(txtEntrada);

        getContentPane().add(spEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, 260, 260));

        btnSiguiente.setBackground(new java.awt.Color(102, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 610, 110, 60));

        txtSalida.setEditable(false);
        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        txtSalida.setAlignmentX(1.0F);
        txtSalida.setAlignmentY(1.0F);
        spSalida.setViewportView(txtSalida);

        getContentPane().add(spSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 430, 270, 70));
        getContentPane().add(txtOP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 60, 28));
        getContentPane().add(txtIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 60, 28));
        getContentPane().add(txtOP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 60, 28));
        getContentPane().add(txtResultadoALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 60, 28));
        getContentPane().add(txtPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 60, 28));
        getContentPane().add(txtMBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 60, 28));
        getContentPane().add(txtMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 60, 28));

        btnEntrada.setBackground(new java.awt.Color(102, 0, 0));
        btnEntrada.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrada.setText("Seleccionar archivo");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 260, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        fondo.setPreferredSize(new java.awt.Dimension(1500, 688));
        fondo.setRequestFocusEnabled(false);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
    contadorSiguiente=+1; 
    
    if(contadorSiguiente==1){
        
    }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        
        List<String> listaLineas=new ArrayList<>();
        listaLineas = lector.presentar();
        String union="";
        for (String linea : listaLineas) {
            union+= "\n" + linea;
        }
        txtEntrada.setText(union);  
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void mostrarDatosALU(){
    
    }
    
    private void mostrarDatosMBR(){
        
    }
    
    private String[] separarDatos(ArrayList<String> listaLineas){
        String[] lineaSeparada=new String[3];
        
        for (String linea : listaLineas) {
            lineaSeparada=linea.split(" ");
            
        }
        return lineaSeparada;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Computador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Computador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Computador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Computador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Computador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane spEntrada;
    private javax.swing.JScrollPane spSalida;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextField txtIR;
    private javax.swing.JTextField txtMAR;
    private javax.swing.JTextField txtMBR;
    private javax.swing.JTextField txtOP1;
    private javax.swing.JTextField txtOP2;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtResultadoALU;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
